framework:
  notifier:
    chatter_transports:
    texter_transports:
    channel_policy:
      # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
      high: ["email"]
      medium: ["email"]
      urgent: ["browser"]
      low: ["email"]
    admin_recipients:
      - { email: admin@example.com }
