security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\GoogleAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_default_target

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/user/register, roles: PUBLIC_ACCESS }
        - { path: ^/user/new, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
