# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        user_profile_image:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false