parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    uploaded_faceid_dir: '%kernel.project_dir%/public/uploads/faceid/temp'
    known_faces_dir: '%kernel.project_dir%/public/uploads/faceid/faces'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Kernel.php"

  App\Security\GoogleAuthenticator:
    arguments:
      $client: '@knpu.oauth2.client.google'
      $em: '@doctrine.orm.entity_manager'
      $router: '@router'
